/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package logmonitor;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.InputStreamReader;
import java.io.OutputStream;
import java.io.PrintStream;
import java.io.PrintWriter;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.SwingUtilities;

/**
 *
 * @author Administrator
 */
public class LogMonitor extends javax.swing.JFrame {

    /**
     * Creates new form LogMonitor
     */
    public LogMonitor() {
        initComponents();
        monitorPanel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooser = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtArea = new javax.swing.JTextArea();
        btnUpload = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        monitorPanel = new javax.swing.JPanel();
        lblLogger = new javax.swing.JLabel();
        txtStart = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSec = new javax.swing.JComboBox();
        btnLogger = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtAlerts = new javax.swing.JTextArea();
        btnReload = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(700, 900));
        setMinimumSize(new java.awt.Dimension(700, 900));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Please enter the searching string (separeted by commas) : ");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, -1, 25));

        txtArea.setColumns(20);
        txtArea.setRows(5);
        jScrollPane1.setViewportView(txtArea);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(351, 25, 280, 68));

        btnUpload.setText("Upload Text");
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        getContentPane().add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 111, -1, -1));

        btnClear.setText("Clear");
        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        getContentPane().add(btnClear, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 111, -1, -1));

        txtStart.setText("Start Monitoring");
        txtStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtStartActionPerformed(evt);
            }
        });

        jLabel3.setText("Choose monitoring time interval (in sec): ");

        txtSec.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "1", "2", "5", "10", "15", "20" }));
        txtSec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSecActionPerformed(evt);
            }
        });

        btnLogger.setText("Choose Logger File");
        btnLogger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggerActionPerformed(evt);
            }
        });

        txtAlerts.setColumns(20);
        txtAlerts.setRows(5);
        jScrollPane3.setViewportView(txtAlerts);

        javax.swing.GroupLayout monitorPanelLayout = new javax.swing.GroupLayout(monitorPanel);
        monitorPanel.setLayout(monitorPanelLayout);
        monitorPanelLayout.setHorizontalGroup(
            monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitorPanelLayout.createSequentialGroup()
                .addGroup(monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monitorPanelLayout.createSequentialGroup()
                        .addGroup(monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(monitorPanelLayout.createSequentialGroup()
                                .addGap(57, 57, 57)
                                .addGroup(monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(monitorPanelLayout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(txtSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(monitorPanelLayout.createSequentialGroup()
                                        .addComponent(btnLogger)
                                        .addGap(66, 66, 66)
                                        .addComponent(lblLogger, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(monitorPanelLayout.createSequentialGroup()
                                .addGap(184, 184, 184)
                                .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 110, Short.MAX_VALUE))
                    .addGroup(monitorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane3)))
                .addContainerGap())
        );
        monitorPanelLayout.setVerticalGroup(
            monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(monitorPanelLayout.createSequentialGroup()
                .addGroup(monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(monitorPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(lblLogger, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, monitorPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnLogger)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(monitorPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtSec, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(txtStart, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                .addContainerGap())
        );

        getContentPane().add(monitorPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 145, 560, -1));

        btnReload.setText("Reload");
        btnReload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReloadActionPerformed(evt);
            }
        });
        getContentPane().add(btnReload, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 710, 90, 40));

        btnExit.setText("Stop Script");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        getContentPane().add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 710, 90, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
        txtArea.setText("");
        
    }//GEN-LAST:event_btnClearActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        PrintWriter out = null;
        try {
            String str = txtArea.getText();
            out = new PrintWriter("C:\\apps\\home\\logs\\choose.txt");
            out.println(str);
            monitorPanel.setVisible(true);
        } catch (FileNotFoundException ex) {
            //Logger.getLogger(LogMonitor.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            out.close();
        }
        
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnLoggerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggerActionPerformed
        int returnVal = fileChooser.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = fileChooser.getSelectedFile();
            try {
                // What to do with the file, e.g. display it in a TextArea
                //textarea.read( new FileReader( file.getAbsolutePath() ), null );
                lblLogger.setText(file.getAbsolutePath());
                lblLogger.setToolTipText(file.getAbsolutePath());
            } catch (Exception ex) {
                System.out.println("problem accessing file"+file.getAbsolutePath());
            }
        } else {
            System.out.println("File access cancelled by user.");
        }
    }//GEN-LAST:event_btnLoggerActionPerformed

    private void txtSecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSecActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSecActionPerformed

    private void txtStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtStartActionPerformed
        //printArea.setVisible(true);
        //redirectSystemStreams();
        try {           
            String sec = txtSec.getSelectedItem().toString();;
            Runtime r = Runtime.getRuntime();
            Process pr = r.exec("C:\\Users\\Administrator\\Desktop\\fileCheck.bat C:\\apps\\home\\logs\\loggenerator.log C:\\apps\\home\\logs\\choose.txt "+sec+" > C:\\mytext.txt");
//            BufferedReader input = new BufferedReader(new InputStreamReader(pr.getInputStream()));
//            while ((line = input.readLine()) != null) {
//                System.out.println(line);       
//                //txtAlerts.append(line);
//                Thread.sleep(200);
//            }
//            
//            input.close();
          
        } catch (IOException ex) {
            //Logger.getLogger(LogMonitor.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_txtStartActionPerformed

    private void btnReloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReloadActionPerformed
        //redirectSystemStreams();
        BufferedReader in = null;
        try {
            in = new BufferedReader(new FileReader("C:\\mytext.txt"));
            String str;
            while ((str = in.readLine()) != null) {
                txtAlerts.append(str+"\n");
                //System.out.println(str);
            }
        } catch (IOException e) {
        } finally {
            try { in.close(); } catch (Exception ex) { }
        }
    }//GEN-LAST:event_btnReloadActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        try {           
            Runtime r = Runtime.getRuntime();
            Process pr = r.exec("TASKKILL /F /IM cmd.exe /T");  
            this.dispose();
        } catch (IOException ex) {
            //Logger.getLogger(LogMonitor.class.getName()).log(Level.SEVERE, null, ex);
        } 
        
    }//GEN-LAST:event_btnExitActionPerformed

    private void updateTextArea(final String text) {
         SwingUtilities.invokeLater(new Runnable() {
           public void run() {
               System.out.println("hello");
             txtAlerts.append(text);
           }
         });
   }
 
    private void redirectSystemStreams() {
      OutputStream out = new OutputStream() {
        @Override
        public void write(int b) throws IOException {
          updateTextArea(String.valueOf((char) b));
        }

        @Override
        public void write(byte[] b, int off, int len) throws IOException {
          updateTextArea(new String(b, off, len));
        }

        @Override
        public void write(byte[] b) throws IOException {
          write(b, 0, b.length);
        }
      };

      System.setOut(new PrintStream(out, true));
      System.setErr(new PrintStream(out, true));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogMonitor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogMonitor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnLogger;
    private javax.swing.JButton btnReload;
    private javax.swing.JButton btnUpload;
    private javax.swing.JFileChooser fileChooser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblLogger;
    private javax.swing.JPanel monitorPanel;
    private javax.swing.JTextArea txtAlerts;
    private javax.swing.JTextArea txtArea;
    private javax.swing.JComboBox txtSec;
    private javax.swing.JButton txtStart;
    // End of variables declaration//GEN-END:variables
}
